### ISSUE TITLE
Does helper of list_alternate work for page?

### ISSUE THREAD

**Issue by dengcb** [ahaasler/hexo-multilingual#21]
In my site: https://dengcb.com, I use list_alternate and it works fine in **`index and archives`**.

```
<% if (config.multilingual) { %>
<div class="column is-narrow">
    <%- list_head_alternates() %>
    <%- list_alternates({
    prepend: '<div class="columns is-mobile is-multiline is-centered">',
    element: '<a class="column" href="%url" hreflang="%lang">'+theme.lang_name+'</a>',
    append: '</div>',
    showCurrent: false
    }) %>
</div>
<% } %>
```

But other pages like **`categories, tags or about`**, it doesn't work.

What can I do if I want to get a alternate link in this pages?

**Comment by ahaasler** [comment]
I haven't had time to look at it yet, did it work for you?

**Comment by dengcb** [comment]
I think it doesn't work, so I write a silly and stable function to convert url from 2 languages.
Because I just need 2 lanuages, so it's just ok for me.

Hope you can see it when you have free time :)
